[package]
name = "libformat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
lazy_static = { workspace = true }
quick-xml = { workspace = true }
quote = "1.0.36"
serde = { workspace = true }
syn = "2.0.66"
xml-rs = "0.8.20"
