[package]
name = "perseus-api"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
url = "2.5.2"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
anyhow.workspace = true
