comment_width = 80
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
chain_width = 80
max_width = 80

fn_params_layout = "Compressed"

reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"