[package]
name = "editor"
version = "1.0.0"
edition = "2021"
authors = ["huangsu <ximisjtu@gmail.com>"]
license = "MIT OR Apache-2.0"
rust-version = "1.72"
publish = false

[[bin]]
name = 'editor'
path = 'src/main.rs'



[dependencies]
libutil = { workspace = true}
libmap = { workspace = true}
libsimulator = { workspace = true}
libwebserver = { workspace = true}
libmodel = { workspace = true}

dashmap.workspace = true
clap.workspace = true
anyhow.workspace = true
clap-handler.workspace = true
clap_complete.workspace = true
time.workspace = true
time-macros.workspace = true
tracing.workspace = true
tracing-core.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }
tracing-appender.workspace = true

jemallocator = "0.5.0"
jemalloc-ctl = "0.5.0"
jemalloc-sys = { version = "0.5.3", features = [
    "stats",
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }
lazy_static.workspace = true
eframe = "0.27.2"
serde = { version = "1.0.200", features = ["derive"] }
