[package]
name = "editor"
version = "1.0.0"
edition = "2021"
authors = ["huangsu <ximisjtu@gmail.com>"]
license = "MIT OR Apache-2.0"
rust-version = "1.72"
publish = false

[[bin]]
name = 'editor'
path = 'src/main.rs'



[dependencies]
libutil = { workspace = true}
libmap = { workspace = true}
libsimulator = { workspace = true}
libwebserver = { workspace = true}
libmodel = { workspace = true}
libformat = { workspace = true}

dashmap.workspace = true
clap.workspace = true
anyhow.workspace = true
clap-handler.workspace = true
clap_complete.workspace = true
time.workspace = true
time-macros.workspace = true
tracing.workspace = true
tracing-core.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }
tracing-appender.workspace = true

#jemallocator = "0.5.0"
#jemalloc-ctl = "0.5.0"
#jemalloc-sys = { version = "0.5.3", features = [
#    "stats",
#    "profiling",
#    "unprefixed_malloc_on_supported_platforms",
#] }
lazy_static.workspace = true
serde = { version = "1.0.200", features = ["derive"] }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }


iced = { version = "0.12.0", features=[ "advanced", "wgpu" ] }
iced_core = "0.13.2"
bytemuck = "1.15.0"
glam = { version="0.27.0", features=[ "bytemuck" ] }
rand = "0.8.5"
image = "0.24.9"
cgmath = "0.18.0"

