import type { Metadata } from "next";
import Script from 'next/script';
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry'

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "环卫仿真",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <AntdRegistry>
        {/* <Script type="text/javascript" src={`https://api.map.baidu.com/api?type=webgl&v=1.0&ak=FjWtc43vXyS5GlZVYxYcTgTmlmYvBcmQ`}></Script> */}
        <body className={inter.className}>
          <script type="text/javascript" src="//api.map.baidu.com/api?type=webgl&v=1.0&ak=FjWtc43vXyS5GlZVYxYcTgTmlmYvBcmQ"></script>
          {children}</body>
      </AntdRegistry>
    </html>
  );
}